#!/bin/bash

# Auto-Build Environment Setup
# Power Flow Visualization Quality Improvement
# Generated by Planner Agent

set -e

echo "========================================"
echo "Power Flow Visualization - Dev Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# Project root
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$PROJECT_ROOT"

echo ""
echo -e "${CYAN}Project Root:${NC} $PROJECT_ROOT"
echo ""

# ============================================
# VERIFY PROJECT FILES
# ============================================

echo -e "${YELLOW}Verifying project files...${NC}"

required_files=(
    "index.html"
    "power_flow_v5.html"
    "power_flow_matpower_v2.html"
    "power_flow_intuitive_v6_fixed.html"
    "scripts/main.js"
)

missing_files=()
for file in "${required_files[@]}"; do
    if [ ! -f "$file" ]; then
        missing_files+=("$file")
    fi
done

if [ ${#missing_files[@]} -ne 0 ]; then
    echo -e "${RED}Missing required files:${NC}"
    for file in "${missing_files[@]}"; do
        echo "  - $file"
    done
    echo ""
    echo -e "${YELLOW}The repository may need to be cloned first:${NC}"
    echo "  git clone https://github.com/lutelute/power_flow_viz.git ."
    exit 1
fi

echo -e "${GREEN}All required files present${NC}"
echo ""

# ============================================
# START LOCAL SERVER
# ============================================

echo -e "${YELLOW}Starting local development server...${NC}"

# Check if port 8000 is in use
if lsof -Pi :8000 -sTCP:LISTEN -t >/dev/null 2>&1; then
    echo -e "${YELLOW}Port 8000 already in use. Attempting to use it...${NC}"
else
    # Start Python HTTP server in background
    python3 -m http.server 8000 &
    SERVER_PID=$!

    # Wait for server to start
    sleep 2

    if kill -0 $SERVER_PID 2>/dev/null; then
        echo -e "${GREEN}Server started (PID: $SERVER_PID)${NC}"
    else
        echo -e "${RED}Failed to start server${NC}"
        exit 1
    fi
fi

echo ""

# ============================================
# SUMMARY
# ============================================

echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo -e "  ${CYAN}Main Application:${NC}     http://localhost:8000"
echo -e "  ${CYAN}MATPOWER Suite:${NC}       http://localhost:8000/power_flow_v5.html"
echo -e "  ${CYAN}Intuitive Visualizer:${NC} http://localhost:8000/power_flow_intuitive_v6_fixed.html"
echo -e "  ${CYAN}DC Analysis:${NC}          http://localhost:8000/dc_accuracy_analysis.html"
echo ""
echo "Key Files:"
echo "  - scripts/main.js      (UI animations)"
echo "  - scripts/ieee_cases.js     (to be created - IEEE test cases)"
echo "  - scripts/power_flow_engine.js (to be created - algorithm engine)"
echo ""
echo "Development Notes:"
echo "  - No build process required - edit HTML/JS directly"
echo "  - Refresh browser to see changes"
echo "  - Check browser console for errors"
echo ""
echo "To stop the server:"
echo "  kill $SERVER_PID (or Ctrl+C)"
echo ""
